#!/usr/bin/env python3
"""Create SPARQL question CSVs for injected ontology contradictions.

This script reads the TTL files produced by
create_inconsistent_ontologies.py and writes one CSV with the
same column format as the regular SPARQL_questions.csv files.

For now only range-violation questions are generated. Class-disjointness and
functional-property inputs are accepted as placeholders for later generators.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

GENEALOGY_NS = "http://www.example.com/genealogy.owl#"
CSV_COLUMNS = [
    "Task ID",
    "Root Entity",
    "Size of ontology TBox",
    "Size of ontology ABox",
    "Task Type",
    "Query Type",
    "Answer Type",
    "SPARQL Query",
    "Predicate",
    "Answer",
    "Min Tag Length",
    "Max Tag Length",
]
URI = r"<([^>]+)>"
TRIPLE_RE = re.compile(rf"{URI}\s+{URI}\s+{URI}\s*\.")
DIFFERENT_RE = re.compile(rf"{URI}\s+owl:differentFrom\s+{URI}\s*\.")
RANGE_METADATA_TRIPLE_RE = re.compile(
    rf"#\s+RANGE_VIOLATION\s+(original|added|removed)\s+{URI}\s+{URI}\s+{URI}"
)
RANGE_METADATA_TYPE_RE = re.compile(rf"#\s+RANGE_VIOLATION\s+support_type\s+{URI}\s+{URI}")
RDF_TYPE = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
RDFS_DOMAIN = "http://www.w3.org/2000/01/rdf-schema#domain"
RDFS_RANGE = "http://www.w3.org/2000/01/rdf-schema#range"
OWL_INVERSE_OF = "http://www.w3.org/2002/07/owl#inverseOf"
OWL_NAMED_INDIVIDUAL = "http://www.w3.org/2002/07/owl#NamedIndividual"
QNAME_URIS = {
    "rdf:type": RDF_TYPE,
    "owl:NamedIndividual": OWL_NAMED_INDIVIDUAL,
    "owl:inverseOf": OWL_INVERSE_OF,
    "rdfs:domain": RDFS_DOMAIN,
    "rdfs:range": RDFS_RANGE,
}


@dataclass(frozen=True)
class Triple:
    subject: str
    predicate: str
    object: str


@dataclass(frozen=True)
class RangeViolationMetadata:
    original: tuple[Triple, ...]
    added: tuple[Triple, ...]
    removed: tuple[Triple, ...]
    support_types: tuple[tuple[str, str], ...]


@dataclass(frozen=True)
class ViolationQuestion:
    task_id: str
    root_entity: str
    tbox_size: int
    abox_size: int
    task_type: str
    query_type: str
    answer_type: str
    sparql_query: str
    predicate: str
    answer: str
    min_tag_length: int = 0
    max_tag_length: int = 0

    def to_row(self) -> dict[str, object]:
        return {
            "Task ID": self.task_id,
            "Root Entity": self.root_entity,
            "Size of ontology TBox": self.tbox_size,
            "Size of ontology ABox": self.abox_size,
            "Task Type": self.task_type,
            "Query Type": self.query_type,
            "Answer Type": self.answer_type,
            "SPARQL Query": self.sparql_query,
            "Predicate": self.predicate,
            "Answer": self.answer,
            "Min Tag Length": self.min_tag_length,
            "Max Tag Length": self.max_tag_length,
        }


def local_name(uri: str) -> str:
    if "#" in uri:
        return uri.rsplit("#", 1)[1]
    return uri.rstrip("/").rsplit("/", 1)[-1]


def predicate_name(uri: str) -> str:
    if uri == RDF_TYPE:
        return "rdf:type"
    return local_name(uri)


def uri_for_name(name: str, predicate: bool = False) -> str:
    if name == "rdf:type":
        return RDF_TYPE
    if name.startswith("http://") or name.startswith("https://"):
        return name
    return GENEALOGY_NS + name


def triple_phrase(triple: Triple) -> str:
    return f"{local_name(triple.subject)} {predicate_name(triple.predicate)} {local_name(triple.object)}"


def split_generated_blocks(text: str) -> tuple[str, str, str]:
    functional_block = ""
    range_block = ""
    class_block = ""

    if "#    Generated functional property violations" in text:
        functional_block = text.split("#    Generated functional property violations", 1)[1]
        if "#    Generated range violations" in functional_block:
            functional_block = functional_block.split("#    Generated range violations", 1)[0]
        if "#    Generated class disjointness violations" in functional_block:
            functional_block = functional_block.split("#    Generated class disjointness violations", 1)[0]
        if "###  Generated by the OWL API" in functional_block:
            functional_block = functional_block.split("###  Generated by the OWL API", 1)[0]

    if "#    Generated range violations" in text:
        range_block = text.split("#    Generated range violations", 1)[1]
        if "#    Generated class disjointness violations" in range_block:
            range_block = range_block.split("#    Generated class disjointness violations", 1)[0]
        if "###  Generated by the OWL API" in range_block:
            range_block = range_block.split("###  Generated by the OWL API", 1)[0]

    if "#    Generated class disjointness violations" in text:
        class_block = text.split("#    Generated class disjointness violations", 1)[1]
        if "###  Generated by the OWL API" in class_block:
            class_block = class_block.split("###  Generated by the OWL API", 1)[0]

    return functional_block, range_block, class_block


def term_to_uri(term: str) -> str | None:
    term = term.strip().rstrip(";,.")
    if term.startswith("<") and term.endswith(">"):
        return term[1:-1]
    return QNAME_URIS.get(term)


def parse_object_uris(rest_objects: str) -> list[str]:
    objects = list(re.findall(URI, rest_objects))
    scrubbed = re.sub(URI, " ", rest_objects)
    for token in re.findall(r"\b(?:rdf|owl|rdfs):[A-Za-z_][A-Za-z0-9_-]*", scrubbed):
        uri = term_to_uri(token)
        if uri is not None:
            objects.append(uri)
    return objects


def parse_uri_triples(text: str) -> list[Triple]:
    triples: list[Triple] = []
    subject: str | None = None
    predicate: str | None = None

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or line.startswith("@"):
            continue

        subject_match = re.match(rf"^{URI}\s*(.*)$", line)
        if subject_match and subject is not None and predicate is not None:
            possible_tail = subject_match.group(2).strip()
            if possible_tail in {"", ",", ";", "."}:
                triples.append(Triple(subject, predicate, subject_match.group(1)))
                if possible_tail == ".":
                    subject = None
                    predicate = None
                continue

        subject_match = re.match(rf"^{URI}\s+(.*)$", line)
        if subject_match and subject is not None and subject_match.group(2).strip().startswith("<"):
            rest = line
        elif subject_match:
            subject = subject_match.group(1)
            rest = subject_match.group(2).strip()
            predicate = None
        else:
            rest = line

        if subject is None:
            continue

        predicate_uri: str | None = None
        rest_objects = ""
        qname_predicate = re.match(r"^((?:rdf|owl|rdfs):[A-Za-z_][A-Za-z0-9_-]*)\s+(.*)$", rest)
        uri_predicate = re.match(rf"^{URI}\s+(.*)$", rest)

        if qname_predicate and term_to_uri(qname_predicate.group(1)) is not None:
            predicate_uri = term_to_uri(qname_predicate.group(1))
            rest_objects = qname_predicate.group(2).strip()
        elif uri_predicate:
            predicate_uri = uri_predicate.group(1)
            rest_objects = uri_predicate.group(2).strip()
        elif predicate is not None:
            predicate_uri = predicate
            rest_objects = rest

        if predicate_uri is None:
            continue

        predicate = predicate_uri
        for obj in parse_object_uris(rest_objects):
            triples.append(Triple(subject, predicate, obj))

        if rest.endswith("."):
            subject = None
            predicate = None

    return triples


def focus_individual_uri(file_stem: str) -> str:
    return GENEALOGY_NS + file_stem.removeprefix("Thing_")


def collect_ranges(triples: Iterable[Triple]) -> dict[str, str]:
    return {triple.subject: triple.object for triple in triples if triple.predicate == RDFS_RANGE}


def collect_domains(triples: Iterable[Triple]) -> dict[str, str]:
    return {triple.subject: triple.object for triple in triples if triple.predicate == RDFS_DOMAIN}


def collect_inverses(triples: Iterable[Triple]) -> dict[str, str]:
    inverses: dict[str, str] = {}
    for triple in triples:
        if triple.predicate == OWL_INVERSE_OF:
            inverses[triple.subject] = triple.object
            inverses[triple.object] = triple.subject
    return inverses


def simple_class_hints(triples: Iterable[Triple]) -> dict[str, set[str]]:
    triples = list(triples)
    ranges = collect_ranges(triples)
    domains = collect_domains(triples)
    inverses = collect_inverses(triples)
    hints: dict[str, set[str]] = {}

    for triple in triples:
        if triple.predicate == RDF_TYPE:
            hints.setdefault(triple.object, set()).add(triple.subject)
            continue

        if triple.predicate in domains:
            hints.setdefault(domains[triple.predicate], set()).add(triple.subject)
        if triple.predicate in ranges:
            hints.setdefault(ranges[triple.predicate], set()).add(triple.object)

        inverse = inverses.get(triple.predicate)
        if inverse is not None:
            if inverse in domains:
                hints.setdefault(domains[inverse], set()).add(triple.object)
            if inverse in ranges:
                hints.setdefault(ranges[inverse], set()).add(triple.subject)

    return hints


def normalized_range_assertions_for_focus(triples: Iterable[Triple], focus_subject: str) -> list[Triple]:
    triples = list(triples)
    ranges = collect_ranges(triples)
    inverses = collect_inverses(triples)
    assertions: list[Triple] = []
    seen: set[tuple[str, str, str]] = set()

    for triple in triples:
        normalized: Triple | None = None
        if triple.subject == focus_subject and triple.predicate in ranges:
            normalized = triple
        elif triple.object == focus_subject and inverses.get(triple.predicate) in ranges:
            normalized = Triple(triple.object, inverses[triple.predicate], triple.subject)

        if normalized is None:
            continue
        key = (normalized.subject, normalized.predicate, normalized.object)
        if key not in seen:
            seen.add(key)
            assertions.append(normalized)

    return assertions


def make_ask_type_query(individual: str, class_uri: str) -> str:
    return f"ASK WHERE {{ <{individual}> <{RDF_TYPE}> <{class_uri}> }}"


def count_tbox_abox(text: str) -> tuple[int, int]:
    tbox_patterns = [
        r"rdf:type\s+owl:Class",
        r"rdf:type\s+owl:ObjectProperty",
        r"rdf:type\s+owl:FunctionalProperty",
        r"rdfs:subClassOf",
        r"rdfs:subPropertyOf",
        r"rdfs:domain",
        r"rdfs:range",
        r"owl:inverseOf",
        r"owl:equivalentClass",
        r"owl:equivalentProperty",
        r"owl:propertyChainAxiom",
        r"owl:disjointWith",
    ]
    tbox_size = sum(len(re.findall(pattern, text)) for pattern in tbox_patterns)
    abox_size = len(re.findall(r"rdf:type\s+owl:NamedIndividual", text))
    return tbox_size, abox_size


def make_select_query(subject: str, predicate: str) -> str:
    return f"SELECT ?x WHERE {{ <{subject}> <{predicate}> ?x }}"


def make_task_id(hop: str, root_entity: str, task_kind: str, subject: str, predicate: str, index: int) -> str:
    return (
        f"{hop}-{root_entity}-{task_kind}-"
        f"{local_name(subject)}-{local_name(predicate)}-{index}-MC"
    )


def parse_range_metadata(text: str) -> RangeViolationMetadata:
    original: list[Triple] = []
    added: list[Triple] = []
    removed: list[Triple] = []
    support_types: list[tuple[str, str]] = []

    for line in text.splitlines():
        triple_match = RANGE_METADATA_TRIPLE_RE.fullmatch(line.strip())
        if triple_match:
            kind, subject, predicate, obj = triple_match.groups()
            triple = Triple(subject, predicate, obj)
            if kind == "original":
                original.append(triple)
            elif kind == "added":
                added.append(triple)
            elif kind == "removed":
                removed.append(triple)
            continue

        type_match = RANGE_METADATA_TYPE_RE.fullmatch(line.strip())
        if type_match:
            support_types.append(type_match.groups())

    return RangeViolationMetadata(
        original=tuple(original),
        added=tuple(added),
        removed=tuple(removed),
        support_types=tuple(support_types),
    )


def load_explanations(explanations_file: Path) -> dict:
    text = explanations_file.read_text(encoding="utf-8")
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        # Some generated Explanations.json files contain duplicate separators
        # between top-level entries, e.g. "},\n,\n  \"key\"". Normalize that
        # narrow formatting issue without changing the source file.
        repaired_text = text
        while True:
            collapsed_text = re.sub(r",\s*,", ",", repaired_text)
            if collapsed_text == repaired_text:
                break
            repaired_text = collapsed_text
        repaired_text = re.sub(r",\s*([}\]])", r"\1", repaired_text)
        return json.loads(repaired_text)


def explanation_mentions_any_original_assertion(explanations: list[list[str]], original_triples: tuple[Triple, ...]) -> bool:
    if not original_triples:
        return False

    phrases = [triple_phrase(triple) for triple in original_triples]
    for explanation in explanations:
        for step in explanation:
            if any(phrase in step for phrase in phrases):
                return True
    return False


def explanation_mentions_any_phrase(explanations: list[list[str]], phrases: set[str]) -> bool:
    for explanation in explanations:
        for step in explanation:
            if any(phrase in step for phrase in phrases):
                return True
    return False


def explanation_belongs_to_root(entry: dict, root_entity: str) -> bool:
    return any(root_entity in task_id for task_id in entry.get("taskIds", []))


def inferred_triple_from_entry(entry: dict) -> Triple | None:
    inferred = entry.get("inferred", {})
    subject_name = inferred.get("subject")
    predicate_name_value = inferred.get("predicate")
    object_name = inferred.get("object")
    if not subject_name or not predicate_name_value or not object_name:
        return None
    return Triple(
        uri_for_name(subject_name),
        uri_for_name(predicate_name_value, predicate=True),
        uri_for_name(object_name),
    )


def build_contradicted_dependency_phrases(
    explanation_entries: list[dict], original_triples: tuple[Triple, ...]
) -> set[str]:
    dependency_phrases = {triple_phrase(triple) for triple in original_triples}

    changed = True
    while changed:
        changed = False
        for entry in explanation_entries:
            if not explanation_mentions_any_phrase(entry.get("explanations", []), dependency_phrases):
                continue
            inferred_triple = inferred_triple_from_entry(entry)
            if inferred_triple is None:
                continue
            phrase = triple_phrase(inferred_triple)
            if phrase not in dependency_phrases:
                dependency_phrases.add(phrase)
                changed = True

    return dependency_phrases


def make_ask_query(subject: str, predicate: str, obj: str) -> str:
    return f"ASK WHERE {{ <{subject}> <{predicate}> <{obj}> }}"


def contradicted_questions_for_file(
    ttl_file: Path,
    hop: str,
    explanations_by_key: dict,
) -> list[ViolationQuestion]:
    text = ttl_file.read_text(encoding="utf-8")
    metadata = parse_range_metadata(text)
    if not metadata.original:
        return []

    root_entity = ttl_file.stem
    tbox_size, abox_size = count_tbox_abox(text)
    questions: list[ViolationQuestion] = []
    seen: set[tuple[str, str, str]] = set()
    index = 1
    root_entries = [
        entry
        for entry in explanations_by_key.values()
        if explanation_belongs_to_root(entry, root_entity)
    ]
    dependency_phrases = build_contradicted_dependency_phrases(root_entries, metadata.original)

    for entry in root_entries:
        inferred_triple = inferred_triple_from_entry(entry)
        if inferred_triple is None:
            continue
        if triple_phrase(inferred_triple) not in dependency_phrases:
            continue
        subject = inferred_triple.subject
        predicate = inferred_triple.predicate
        obj = inferred_triple.object
        key = (subject, predicate, obj)
        if key in seen:
            continue
        seen.add(key)

        questions.append(
            ViolationQuestion(
                task_id=(
                    f"{hop}-{root_entity}-contradicted-inference-"
                    f"{local_name(subject)}-{predicate_name(predicate)}-{local_name(obj)}-{index}-BIN"
                ),
                root_entity=root_entity,
                tbox_size=tbox_size,
                abox_size=abox_size,
                task_type="Contradicted Inference",
                query_type="CONTRADICTED_INFERENCE",
                answer_type="BIN",
                sparql_query=make_ask_query(subject, predicate, obj),
                predicate=predicate_name(predicate),
                answer="UNKNOWN",
            )
        )
        index += 1

    return questions


def parse_functional_questions(text: str, root_entity: str, hop: str, tbox_size: int, abox_size: int) -> list[ViolationQuestion]:
    functional_block, _, _ = split_generated_blocks(text)
    if not functional_block.strip():
        return []

    questions: list[ViolationQuestion] = []
    lines = [line.strip() for line in functional_block.splitlines() if line.strip()]
    index = 1
    i = 0
    while i < len(lines):
        triple_match = TRIPLE_RE.fullmatch(lines[i])
        if not triple_match:
            i += 1
            continue

        subject, predicate, second_object = triple_match.groups()
        original_object = ""
        if i + 1 < len(lines):
            diff_match = DIFFERENT_RE.fullmatch(lines[i + 1])
            if diff_match and diff_match.group(1) == second_object:
                original_object = diff_match.group(2)
                i += 1

        answers = [local_name(second_object)]
        if original_object:
            answers = [local_name(original_object), local_name(second_object)]

        questions.append(
            ViolationQuestion(
                task_id=make_task_id(hop, root_entity, "functional-violation", subject, predicate, index),
                root_entity=root_entity,
                tbox_size=tbox_size,
                abox_size=abox_size,
                task_type="Functional Property Violation",
                query_type="CONTRADICTED_FUNCTIONAL_PROP_VIOLATION",
                answer_type="MC",
                sparql_query=make_select_query(subject, predicate),
                predicate=local_name(predicate),
                answer="; ".join(answers),
            )
        )
        index += 1
        i += 1

    return questions


def parse_range_questions(text: str, root_entity: str, hop: str, tbox_size: int, abox_size: int) -> list[ViolationQuestion]:
    _, range_block, _ = split_generated_blocks(text)
    if not range_block.strip():
        return []

    questions: list[ViolationQuestion] = []
    index = 1
    current_subject = ""
    for raw_line in range_block.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue

        full_triple_match = TRIPLE_RE.fullmatch(line)
        if full_triple_match:
            subject, predicate, violating_object = full_triple_match.groups()
            if predicate == RDF_TYPE or not predicate.startswith(GENEALOGY_NS):
                continue

            questions.append(
                ViolationQuestion(
                    task_id=make_task_id(hop, root_entity, "range-violation", subject, predicate, index),
                    root_entity=root_entity,
                    tbox_size=tbox_size,
                    abox_size=abox_size,
                    task_type="Range Violation",
                    query_type="CONTRADICTED_RANGE_VIOLATION",
                    answer_type="MC",
                    sparql_query=make_select_query(subject, predicate),
                    predicate=local_name(predicate),
                    answer=local_name(violating_object),
                )
            )
            index += 1
            continue

        subject_match = re.match(rf"^{URI}\s+rdf:type\b", line)
        if subject_match:
            current_subject = subject_match.group(1)
            continue

        triple_match = re.match(rf"^{URI}\s+{URI}\s*\.", line)
        if not triple_match or not current_subject:
            continue

        predicate, violating_object = triple_match.groups()
        if not predicate.startswith(GENEALOGY_NS):
            continue

        questions.append(
            ViolationQuestion(
                task_id=make_task_id(hop, root_entity, "range-violation", current_subject, predicate, index),
                root_entity=root_entity,
                tbox_size=tbox_size,
                abox_size=abox_size,
                task_type="Range Violation",
                query_type="CONTRADICTED_RANGE_VIOLATION",
                answer_type="MC",
                sparql_query=make_select_query(current_subject, predicate),
                predicate=local_name(predicate),
                answer=local_name(violating_object),
            )
        )
        index += 1

    return questions


def parse_class_disjointness_questions(
    text: str, root_entity: str, hop: str, tbox_size: int, abox_size: int
) -> list[ViolationQuestion]:
    _, _, class_block = split_generated_blocks(text)
    if not class_block.strip():
        return []

    questions: list[ViolationQuestion] = []
    index = 1
    for raw_line in class_block.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue

        qname_type_match = re.fullmatch(rf"{URI}\s+rdf:type\s+{URI}\s*\.", line)
        full_triple_match = TRIPLE_RE.fullmatch(line)
        if qname_type_match:
            individual, class_uri = qname_type_match.groups()
        elif full_triple_match:
            individual, predicate, class_uri = full_triple_match.groups()
            if predicate != RDF_TYPE:
                continue
        else:
            continue

        questions.append(
            ViolationQuestion(
                task_id=(
                    f"{hop}-{root_entity}-class-disjointness-"
                    f"{local_name(individual)}-rdf:type-{local_name(class_uri)}-{index}-BIN"
                ),
                root_entity=root_entity,
                tbox_size=tbox_size,
                abox_size=abox_size,
                task_type="Class Disjointness Violation",
                query_type="CONTRADICTED_CLASS_DISJOINTNESS",
                answer_type="BIN",
                sparql_query=make_ask_type_query(individual, class_uri),
                predicate="rdf:type",
                answer="UNKNOWN",
            )
        )
        index += 1

    return questions


def questions_for_file(ttl_file: Path, hop: str) -> list[ViolationQuestion]:
    text = ttl_file.read_text(encoding="utf-8")
    root_entity = ttl_file.stem
    tbox_size, abox_size = count_tbox_abox(text)
    return [
        *parse_range_questions(text, root_entity, hop, tbox_size, abox_size),
    ]


def no_longer_inferable_questions_for_file(
    original_ttl_file: Path, range_ttl_file: Path, hop: str
) -> list[ViolationQuestion]:
    original_text = original_ttl_file.read_text(encoding="utf-8")
    range_text = range_ttl_file.read_text(encoding="utf-8")
    original_triples = parse_uri_triples(original_text)
    range_triples = parse_uri_triples(range_text)
    original_ranges = collect_ranges(original_triples)
    range_triple_keys = {(triple.subject, triple.predicate, triple.object) for triple in range_triples}
    surviving_type_hints = simple_class_hints(range_triples)
    root_entity = original_ttl_file.stem
    focus_subject = focus_individual_uri(root_entity)
    tbox_size, abox_size = count_tbox_abox(range_text)

    questions: list[ViolationQuestion] = []
    seen: set[tuple[str, str]] = set()
    index = 1
    for assertion in normalized_range_assertions_for_focus(original_triples, focus_subject):
        if (assertion.subject, assertion.predicate, assertion.object) in range_triple_keys:
            continue

        range_class = original_ranges.get(assertion.predicate)
        if range_class is None:
            continue
        if assertion.object in surviving_type_hints.get(range_class, set()):
            continue

        key = (assertion.object, range_class)
        if key in seen:
            continue
        seen.add(key)

        questions.append(
            ViolationQuestion(
                task_id=(
                    f"{hop}-{root_entity}-no-longer-inferable-"
                    f"{local_name(assertion.object)}-rdf:type-{local_name(range_class)}-{index}-BIN"
                ),
                root_entity=root_entity,
                tbox_size=tbox_size,
                abox_size=abox_size,
                task_type="No Longer Inferable Membership",
                query_type="NO_LONGER_INFERABLE_RANGE_MEMBERSHIP",
                answer_type="BIN",
                sparql_query=make_ask_type_query(assertion.object, range_class),
                predicate="rdf:type",
                answer="UNKNOWN",
            )
        )
        index += 1

    return questions


def write_csv(questions: list[ViolationQuestion], output_file: Path) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with output_file.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=CSV_COLUMNS, quoting=csv.QUOTE_ALL)
        writer.writeheader()
        for question in questions:
            writer.writerow(question.to_row())


def collect_questions_from_directory(input_dir: Path, hop: str, explanations_by_key: dict) -> list[ViolationQuestion]:
    questions: list[ViolationQuestion] = []
    for ttl_file in sorted(input_dir.glob("*.ttl")):
        questions.extend(contradicted_questions_for_file(ttl_file, hop, explanations_by_key))
    return questions


def process_dataset(input_dir: Path, output_file: Path, hop: str) -> int:
    questions = collect_questions_from_directory(input_dir, hop, {})
    write_csv(questions, output_file)
    return len(questions)


def process_no_longer_inferable_dataset(
    original_input_dir: Path, range_input_dir: Path, output_file: Path, hop: str
) -> int:
    questions: list[ViolationQuestion] = []
    for original_ttl_file in sorted(original_input_dir.glob("*.ttl")):
        range_ttl_file = range_input_dir / original_ttl_file.name
        if range_ttl_file.is_file():
            questions.extend(no_longer_inferable_questions_for_file(original_ttl_file, range_ttl_file, hop))
    write_csv(questions, output_file)
    return len(questions)


def main() -> None:
    parser = argparse.ArgumentParser(description="Create contradicted SPARQL CSVs grouped by violation type.")
    parser.add_argument(
        "--one-hop-range-dir",
        type=Path,
        required=True,
        help="Directory containing 1-hop range-violation TTL files.",
    )
    parser.add_argument(
        "--two-hop-range-dir",
        type=Path,
        required=True,
        help="Directory containing 2-hop range-violation TTL files.",
    )
    parser.add_argument(
        "--one-hop-explanations",
        type=Path,
        required=True,
        help="Explanations.json file for the original 1-hop TTL files.",
    )
    parser.add_argument(
        "--two-hop-explanations",
        type=Path,
        required=True,
        help="Explanations.json file for the original 2-hop TTL files.",
    )
    parser.add_argument(
        "--one-hop-class-disjointness-dir",
        type=Path,
        required=True,
        help="Directory containing 1-hop class-disjointness TTL files.",
    )
    parser.add_argument(
        "--two-hop-class-disjointness-dir",
        type=Path,
        required=True,
        help="Directory containing 2-hop class-disjointness TTL files.",
    )
    parser.add_argument(
        "--one-hop-func-prop-dir",
        type=Path,
        required=True,
        help="Directory containing 1-hop functional-property-violation TTL files.",
    )
    parser.add_argument(
        "--two-hop-func-prop-dir",
        type=Path,
        required=True,
        help="Directory containing 2-hop functional-property-violation TTL files.",
    )
    parser.add_argument(
        "--one-hop-output-dir",
        type=Path,
        required=True,
        help="Directory where 1-hop contradicted question CSVs will be written.",
    )
    parser.add_argument(
        "--two-hop-output-dir",
        type=Path,
        required=True,
        help="Directory where 2-hop contradicted question CSVs will be written.",
    )
    args = parser.parse_args()

    jobs = [
        ("1hop", "range", args.one_hop_range_dir),
        ("2hop", "range", args.two_hop_range_dir),
        ("1hop", "class_disjointness", args.one_hop_class_disjointness_dir),
        ("2hop", "class_disjointness", args.two_hop_class_disjointness_dir),
        ("1hop", "functional_property", args.one_hop_func_prop_dir),
        ("2hop", "functional_property", args.two_hop_func_prop_dir),
    ]

    for _, _, input_dir in jobs:
        if not input_dir.is_dir():
            raise FileNotFoundError(f"Missing input directory: {input_dir}")
    if not args.one_hop_explanations.is_file():
        raise FileNotFoundError(f"Missing explanations file: {args.one_hop_explanations}")
    if not args.two_hop_explanations.is_file():
        raise FileNotFoundError(f"Missing explanations file: {args.two_hop_explanations}")

    explanations_by_hop = {
        "1hop": load_explanations(args.one_hop_explanations),
        "2hop": load_explanations(args.two_hop_explanations),
    }

    questions_by_hop_and_type: dict[str, dict[str, list[ViolationQuestion]]] = {
        "1hop": {"range": [], "class_disjointness": [], "functional_property": []},
        "2hop": {"range": [], "class_disjointness": [], "functional_property": []},
    }
    for hop, violation_type, input_dir in jobs:
        if violation_type == "range":
            directory_questions = collect_questions_from_directory(input_dir, hop, explanations_by_hop[hop])
        else:
            directory_questions = []
        questions_by_hop_and_type[hop][violation_type].extend(directory_questions)
        print(f"{hop}: collected {len(directory_questions)} questions from {input_dir}")

    output_files = {
        "1hop": {
            "range": args.one_hop_output_dir / "SPARQL_questions_range_violation.csv",
            "class_disjointness": args.one_hop_output_dir / "SPARQL_question_class_dis.csv",
            "functional_property": args.one_hop_output_dir / "SPARQL_question_func_prop_violation.csv",
        },
        "2hop": {
            "range": args.two_hop_output_dir / "SPARQL_questions_range_violation.csv",
            "class_disjointness": args.two_hop_output_dir / "SPARQL_question_class_dis.csv",
            "functional_property": args.two_hop_output_dir / "SPARQL_question_func_prop_violation.csv",
        },
    }

    for hop, outputs_by_type in output_files.items():
        for violation_type, output_file in outputs_by_type.items():
            questions = questions_by_hop_and_type[hop][violation_type]
            write_csv(questions, output_file)
            print(f"Done: wrote {len(questions)} {hop} {violation_type} questions to {output_file}")


if __name__ == "__main__":
    main()
